name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GO_VERSION: '1.24'

jobs:
  lint:
    name: ${{ matrix.service }}_lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [coursemaker, coursereader, roadbuilder, searchengine, skilltracker, teamhub]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run golangci-lint on ${{ matrix.service }}
        run: |
          # переходить в директорию не обязательно — можно передать путь напрямую
          golangci-lint run --config ./.golangci.yml ./${{ matrix.service }}

  test:
    name: ${{ matrix.service }}_test
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [coursemaker, coursereader, roadbuilder, searchengine, skilltracker, teamhub]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests for ${{ matrix.service }}
        run: |
          go test -v ./${{ matrix.service }}/...

  build:
    name: ${{ matrix.service }}_build
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [coursemaker, coursereader, roadbuilder, searchengine, skilltracker, teamhub]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build ${{ matrix.service }}
        run: |
          # создаём папку для бинарей
          mkdir -p bin
          go build -o bin/${{ matrix.service }} ./${{ matrix.service }}
