name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GO_VERSION: '1.24'

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      changed_service: ${{ steps.choose.outputs.changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: paths
        uses: dorny/paths-filter@v2
        with:
          filters: |
            coursemaker:  [ 'coursemaker/**' ]
            coursereader: [ 'coursereader/**' ]
            roadbuilder:  [ 'roadbuilder/**' ]
            searchengine: [ 'searchengine/**' ]
            skilltracker: [ 'skilltracker/**' ]
            teamhub:      [ 'teamhub/**' ]
      - id: choose
        run: |
          for svc in coursemaker coursereader roadbuilder searchengine skilltracker teamhub; do
            if [[ "${{ steps.paths.outputs[svc] }}" == "true" ]]; then
              echo "changed=$svc" >> $GITHUB_OUTPUT
              exit 0
            fi
          done
          echo "changed=" >> $GITHUB_OUTPUT

  lint:
    needs: filter
    if: ${{ needs.filter.outputs.changed_service != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.64.8
          args: >-
            --config ./.golangci.yml
            ./${{ needs.filter.outputs.changed_service }}/...

  test:
    needs: lint
    if: ${{ needs.filter.outputs.changed_service != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go test -v ./${{ needs.filter.outputs.changed_service }}/...

  build:
    needs: test
    if: ${{ needs.filter.outputs.changed_service != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: |
          mkdir -p bin
          go build -o bin/${{ needs.filter.outputs.changed_service }} ./${{ needs.filter.outputs.changed_service }}
